### ISSUE TITLE
Does not work with promise form

### ISSUE THREAD

**Issue by joebowbeer** [mongoosejs/mongoose-async-hooks#6]
As I mentioned [here](https://github.com/Automattic/mongoose/issues/5929#issuecomment-500536221), this plugin depends on `$wrapCallback`, which has no effect if promises are used instead of callbacks.

I wrote a test to demonstrate:

https://github.com/joebowbeer/mongoose-async-hooks/blob/joebowbeer-test-async/test/example.test.js

Why not leverage mongoose middleware for this plugin?

**Comment by vkarpov15** [comment]
I opened up an issue in the main Mongoose repo to track this. You're right, this is a big limitation in this plugin.

**Comment by vkarpov15** [comment]
This will work in Mongoose 5.7.2, I put in a fix where we call `$wrapCallback` for both promises and callbacks :+1:

**Comment by joebowbeer** [comment]
@vkarpov15 Thanks! When will you `npm publish` 5.7.2?

**Comment by vkarpov15** [comment]
Already published :+1:

**Comment by joebowbeer** [comment]
@vkarpov15 I don't see it at https://www.npmjs.com/package/mongoose

And neither does my Travis build:

`npm ERR! notarget No matching version found for mongoose@^5.7.2.`

**Comment by vkarpov15** [comment]
@joebowbeer sorry for the trouble. Try Mongoose 5.7.3?

**Comment by joebowbeer** [comment]
@vkarpov15 mongoose 5.7.3 passed this test. Thanks!
